install docker cli

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
@@ -39,6 +39,16 @@ pipeline {
       }
       steps {
         script {
+            // Install the Docker CLI client inside the Maven container runner dynamically
+            sh '''
+               if ! command -v docker &> /dev/null; then
+                   echo "Docker CLI not found. Installing..."
+                   apt-get update && apt-get install -y curl
+                   curl -fsSL https://docker.com -o get-docker.sh
+                   sh get-docker.sh --cli
+               fi
+            '''
+
             sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && docker build -t ${DOCKER_IMAGE} .'
             def dockerImage = docker.image("${DOCKER_IMAGE}")
             docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
